import { College } from "@/types";

export const colleges: College[] = [
  {
    id: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    location: { city: "Mumbai", state: "Maharashtra" },
    type: "Government",
    established: 1958,
    rating: 4.8,
    reviewCount: 1240,
    fees: { btech: 230000, mtech: 22000, mba: 250000 },
    courses: [
      { name: "B.Tech Computer Science", duration: "4 Years", seats: 120, fees: 230000, eligibility: "JEE Advanced" },
      { name: "B.Tech Electrical Engineering", duration: "4 Years", seats: 80, fees: 230000, eligibility: "JEE Advanced" },
      { name: "B.Tech Mechanical Engineering", duration: "4 Years", seats: 80, fees: 230000, eligibility: "JEE Advanced" },
      { name: "M.Tech", duration: "2 Years", seats: 200, fees: 22000, eligibility: "GATE" },
      { name: "MBA", duration: "2 Years", seats: 60, fees: 250000, eligibility: "CAT" },
    ],
    placements: {
      averagePackage: 2100000,
      highestPackage: 25000000,
      medianPackage: 1800000,
      placementRate: 98,
      topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Apple"],
    },
    ranking: { nirf: 3, qs: 118, india: 1 },
    accreditation: ["NAAC A++", "NBA", "UGC"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Incubation Center", "Hospital"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    logo: "IIT-B",
    description: "IIT Bombay is one of the premier engineering institutions in India, known for its cutting-edge research, world-class faculty, and outstanding alumni network spanning global corporations and startups.",
    highlights: ["Top 3 NIRF Ranking", "₹25 LPA Highest Package", "98% Placement Rate", "World-class Research"],
    cutoffs: [
      { exam: "JEE Advanced", year: 2024, category: "General", rank: 67, branch: "Computer Science" },
      { exam: "JEE Advanced", year: 2024, category: "General", rank: 312, branch: "Electrical" },
      { exam: "JEE Advanced", year: 2024, category: "OBC", rank: 45, branch: "Computer Science" },
      { exam: "JEE Advanced", year: 2024, category: "SC", rank: 112, branch: "Computer Science" },
    ],
    reviews: [
      {
        id: "r1",
        author: "Rahul Sharma",
        avatar: "RS",
        rating: 5,
        date: "2024-03-15",
        title: "Best decision of my life",
        content: "The academic rigor here is unmatched. Professors are world-class researchers who genuinely care about students. The peer learning environment is exceptional — surrounded by brilliant minds pushes you to grow constantly.",
        pros: ["Excellent faculty", "Great peer network", "Amazing placements", "World-class research"],
        cons: ["Extremely competitive", "High academic pressure", "Expensive city"],
        batch: "2023",
        course: "B.Tech CSE",
        helpful: 234,
      },
      {
        id: "r2",
        author: "Priya Mehta",
        avatar: "PM",
        rating: 4,
        date: "2024-01-20",
        title: "Transformative experience",
        content: "Four years at IIT Bombay completely transformed how I think and approach problems. The internship opportunities, hackathons, and startup culture on campus are incredible.",
        pros: ["Startup ecosystem", "Research opportunities", "Strong alumni network"],
        cons: ["Work-life balance can be tough", "Limited seats in popular courses"],
        batch: "2022",
        course: "B.Tech EE",
        helpful: 189,
      },
    ],
    tags: ["IIT", "Top Ranked", "Research", "Placements", "Engineering"],
    approved: true,
  },
  {
    id: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    location: { city: "New Delhi", state: "Delhi" },
    type: "Government",
    established: 1961,
    rating: 4.7,
    reviewCount: 980,
    fees: { btech: 220000, mtech: 18000, mba: 220000 },
    courses: [
      { name: "B.Tech Computer Science", duration: "4 Years", seats: 80, fees: 220000, eligibility: "JEE Advanced" },
      { name: "B.Tech Electrical Engineering", duration: "4 Years", seats: 80, fees: 220000, eligibility: "JEE Advanced" },
      { name: "B.Tech Chemical Engineering", duration: "4 Years", seats: 70, fees: 220000, eligibility: "JEE Advanced" },
      { name: "M.Tech", duration: "2 Years", seats: 180, fees: 18000, eligibility: "GATE" },
    ],
    placements: {
      averagePackage: 1950000,
      highestPackage: 22000000,
      medianPackage: 1700000,
      placementRate: 97,
      topRecruiters: ["Amazon", "Microsoft", "Adobe", "Qualcomm", "Flipkart"],
    },
    ranking: { nirf: 2, qs: 174, india: 2 },
    accreditation: ["NAAC A++", "NBA", "UGC"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Incubation Center"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    logo: "IIT-D",
    description: "IIT Delhi, located in the heart of India's capital, is consistently ranked among the top engineering institutes. Its proximity to India's tech and business hub gives students unparalleled industry exposure.",
    highlights: ["NIRF Rank 2", "Delhi Location", "₹22 LPA Highest Package", "Government Institute"],
    cutoffs: [
      { exam: "JEE Advanced", year: 2024, category: "General", rank: 54, branch: "Computer Science" },
      { exam: "JEE Advanced", year: 2024, category: "General", rank: 280, branch: "Electrical" },
      { exam: "JEE Advanced", year: 2024, category: "OBC", rank: 38, branch: "Computer Science" },
      { exam: "JEE Advanced", year: 2024, category: "SC", rank: 98, branch: "Computer Science" },
    ],
    reviews: [
      {
        id: "r3",
        author: "Ankit Gupta",
        avatar: "AG",
        rating: 5,
        date: "2024-02-10",
        title: "Exceptional opportunities",
        content: "Being in Delhi gives us access to incredible internship and placement opportunities. The faculty is top-notch and research culture is strong.",
        pros: ["Prime location", "Industry connections", "Strong alumni"],
        cons: ["Competitive atmosphere", "High cost of living nearby"],
        batch: "2024",
        course: "B.Tech CSE",
        helpful: 167,
      },
    ],
    tags: ["IIT", "Top Ranked", "Delhi", "Engineering", "Research"],
    approved: true,
  },
  {
    id: "bits-pilani",
    name: "Birla Institute of Technology and Science",
    shortName: "BITS Pilani",
    location: { city: "Pilani", state: "Rajasthan" },
    type: "Deemed",
    established: 1964,
    rating: 4.5,
    reviewCount: 1560,
    fees: { btech: 580000, mtech: 320000 },
    courses: [
      { name: "B.E. Computer Science", duration: "4 Years", seats: 150, fees: 580000, eligibility: "BITSAT" },
      { name: "B.E. Electronics & Communication", duration: "4 Years", seats: 120, fees: 580000, eligibility: "BITSAT" },
      { name: "B.Pharma", duration: "4 Years", seats: 80, fees: 520000, eligibility: "BITSAT" },
      { name: "M.E.", duration: "2 Years", seats: 100, fees: 320000, eligibility: "GATE/BITSAT" },
    ],
    placements: {
      averagePackage: 1650000,
      highestPackage: 18000000,
      medianPackage: 1400000,
      placementRate: 95,
      topRecruiters: ["Google", "Microsoft", "Oracle", "Cisco", "Deutsche Bank"],
    },
    ranking: { nirf: 24, india: 8 },
    accreditation: ["NAAC A", "UGC", "NBA"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Industry Collaboration Centers"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    logo: "BITS",
    description: "BITS Pilani is one of India's premier private technical universities, known for its unique Practice School program that provides students with industry exposure at leading companies across India and abroad.",
    highlights: ["Practice School Program", "Flexible Curriculum", "Strong Industry Ties", "Alumni Network"],
    cutoffs: [
      { exam: "BITSAT", year: 2024, category: "General", rank: 285, branch: "Computer Science" },
      { exam: "BITSAT", year: 2024, category: "General", rank: 312, branch: "Electronics" },
    ],
    reviews: [
      {
        id: "r4",
        author: "Shreya Kapoor",
        avatar: "SK",
        rating: 5,
        date: "2024-04-05",
        title: "Practice School is a game changer",
        content: "The PS program at BITS is unmatched. I did two industry internships through PS and had a job offer before graduation. The dual degree option and flexible curriculum are major advantages.",
        pros: ["Practice School", "Flexible curriculum", "Dual degree option", "Strong placements"],
        cons: ["High fees", "Remote location", "Limited PhD programs"],
        batch: "2023",
        course: "B.E. CS",
        helpful: 312,
      },
    ],
    tags: ["Deemed", "Private", "Practice School", "Engineering", "Top Private"],
    approved: true,
  },
  {
    id: "nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    shortName: "NIT Trichy",
    location: { city: "Tiruchirappalli", state: "Tamil Nadu" },
    type: "Government",
    established: 1964,
    rating: 4.4,
    reviewCount: 890,
    fees: { btech: 145000, mtech: 45000 },
    courses: [
      { name: "B.Tech Computer Science", duration: "4 Years", seats: 90, fees: 145000, eligibility: "JEE Main" },
      { name: "B.Tech Mechanical Engineering", duration: "4 Years", seats: 120, fees: 145000, eligibility: "JEE Main" },
      { name: "B.Tech Civil Engineering", duration: "4 Years", seats: 100, fees: 145000, eligibility: "JEE Main" },
      { name: "M.Tech", duration: "2 Years", seats: 160, fees: 45000, eligibility: "GATE" },
    ],
    placements: {
      averagePackage: 1200000,
      highestPackage: 12000000,
      medianPackage: 1000000,
      placementRate: 90,
      topRecruiters: ["TCS", "Infosys", "Wipro", "L&T", "Samsung"],
    },
    ranking: { nirf: 9, india: 5 },
    accreditation: ["NAAC A++", "NBA", "UGC"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Cultural Center"],
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80",
    logo: "NIT-T",
    description: "NIT Trichy is consistently ranked as the best NIT in India. With its beautiful campus along the Cauvery river and strong academic tradition, it offers excellent technical education at affordable fees.",
    highlights: ["Best NIT in India", "Affordable Fees", "Strong Alumni", "Beautiful Campus"],
    cutoffs: [
      { exam: "JEE Main", year: 2024, category: "General", rank: 8500, branch: "Computer Science" },
      { exam: "JEE Main", year: 2024, category: "General", rank: 15000, branch: "Mechanical" },
      { exam: "JEE Main", year: 2024, category: "OBC", rank: 5200, branch: "Computer Science" },
      { exam: "JEE Main", year: 2024, category: "SC", rank: 2100, branch: "Computer Science" },
    ],
    reviews: [
      {
        id: "r5",
        author: "Karthik Raj",
        avatar: "KR",
        rating: 4,
        date: "2024-03-01",
        title: "Affordable quality education",
        content: "NIT Trichy offers world-class education at very affordable fees. The campus culture is vibrant, fests are amazing, and placement opportunities are excellent for a government college.",
        pros: ["Affordable fees", "Good placements", "Vibrant campus life", "Strong faculty"],
        cons: ["Remote location", "Less industry exposure than IITs"],
        batch: "2023",
        course: "B.Tech CSE",
        helpful: 145,
      },
    ],
    tags: ["NIT", "Government", "Affordable", "Top NIT", "Engineering"],
    approved: true,
  },
  {
    id: "vit-vellore",
    name: "Vellore Institute of Technology",
    shortName: "VIT Vellore",
    location: { city: "Vellore", state: "Tamil Nadu" },
    type: "Deemed",
    established: 1984,
    rating: 4.1,
    reviewCount: 2100,
    fees: { btech: 395000, mtech: 185000 },
    courses: [
      { name: "B.Tech Computer Science", duration: "4 Years", seats: 400, fees: 395000, eligibility: "VITEEE" },
      { name: "B.Tech ECE", duration: "4 Years", seats: 300, fees: 395000, eligibility: "VITEEE" },
      { name: "B.Tech Mechanical", duration: "4 Years", seats: 250, fees: 395000, eligibility: "VITEEE" },
      { name: "M.Tech", duration: "2 Years", seats: 500, fees: 185000, eligibility: "VITEEE/GATE" },
    ],
    placements: {
      averagePackage: 800000,
      highestPackage: 8000000,
      medianPackage: 650000,
      placementRate: 85,
      topRecruiters: ["TCS", "Infosys", "Wipro", "CTS", "HCL"],
    },
    ranking: { nirf: 11, india: 9 },
    accreditation: ["NAAC A++", "UGC"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Shopping Mall", "Hospital"],
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    logo: "VIT",
    description: "VIT Vellore is one of India's largest private universities, known for its state-of-the-art infrastructure, global collaborations, and massive placement drive that attracts hundreds of companies.",
    highlights: ["2000+ Acres Campus", "Global Collaborations", "Mass Recruitment", "Modern Infrastructure"],
    cutoffs: [
      { exam: "VITEEE", year: 2024, category: "General", rank: 5000, branch: "Computer Science" },
      { exam: "VITEEE", year: 2024, category: "General", rank: 12000, branch: "ECE" },
    ],
    reviews: [
      {
        id: "r6",
        author: "Divya Nair",
        avatar: "DN",
        rating: 4,
        date: "2024-02-28",
        title: "Great infrastructure, good placements",
        content: "The campus is massive and has world-class facilities. The placement cell is very active and placement percentage is consistently high. Good choice if you want to be placed in a reputed IT company.",
        pros: ["Excellent infrastructure", "High placement numbers", "Good college life", "Research opportunities"],
        cons: ["High fees", "Large batch size means less individual attention"],
        batch: "2023",
        course: "B.Tech CSE",
        helpful: 98,
      },
    ],
    tags: ["Deemed", "Private", "Large Campus", "Engineering", "Mass Placements"],
    approved: true,
  },
  {
    id: "iim-ahmedabad",
    name: "Indian Institute of Management Ahmedabad",
    shortName: "IIM Ahmedabad",
    location: { city: "Ahmedabad", state: "Gujarat" },
    type: "Government",
    established: 1961,
    rating: 4.9,
    reviewCount: 760,
    fees: { mba: 2500000 },
    courses: [
      { name: "MBA (PGP)", duration: "2 Years", seats: 385, fees: 2500000, eligibility: "CAT" },
      { name: "MBA (Executive)", duration: "1 Year", seats: 75, fees: 3200000, eligibility: "GMAT/CAT" },
      { name: "PhD", duration: "5 Years", seats: 25, fees: 50000, eligibility: "CAT/GMAT/GRE" },
    ],
    placements: {
      averagePackage: 3200000,
      highestPackage: 90000000,
      medianPackage: 2900000,
      placementRate: 100,
      topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "Amazon"],
    },
    ranking: { nirf: 1, india: 1 },
    accreditation: ["AACSB", "EQUIS", "NAAC A++"],
    facilities: ["Library", "Hostel", "Sports Complex", "Case Study Rooms", "Bloomberg Terminal"],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    logo: "IIM-A",
    description: "IIM Ahmedabad is Asia's premier management institution. Known for its rigorous case-based pedagogy, IIMA produces leaders who shape industries across the globe.",
    highlights: ["#1 Management Institute", "₹90 LPA Highest Package", "100% Placement", "Global Alumni"],
    cutoffs: [
      { exam: "CAT", year: 2024, category: "General", rank: 99, branch: "MBA" },
      { exam: "CAT", year: 2024, category: "OBC", rank: 97, branch: "MBA" },
    ],
    reviews: [
      {
        id: "r7",
        author: "Vikas Malhotra",
        avatar: "VM",
        rating: 5,
        date: "2024-01-15",
        title: "The Harvard of India",
        content: "IIMA lives up to its legendary reputation. Two years of intense learning, exceptional peer group, and a life-changing placement. The alumni network is your biggest asset for life.",
        pros: ["Best faculty", "Peer learning", "Brand value", "Placement"],
        cons: ["Extremely high fees", "Stressful first year"],
        batch: "2023",
        course: "MBA PGP",
        helpful: 445,
      },
    ],
    tags: ["IIM", "MBA", "Top Ranked", "Management", "Government"],
    approved: true,
  },
  {
    id: "srm-chennai",
    name: "SRM Institute of Science and Technology",
    shortName: "SRM Chennai",
    location: { city: "Chennai", state: "Tamil Nadu" },
    type: "Deemed",
    established: 1985,
    rating: 3.9,
    reviewCount: 1870,
    fees: { btech: 350000, mtech: 160000 },
    courses: [
      { name: "B.Tech Computer Science", duration: "4 Years", seats: 600, fees: 350000, eligibility: "SRMJEEE" },
      { name: "B.Tech Biomedical Engineering", duration: "4 Years", seats: 120, fees: 350000, eligibility: "SRMJEEE" },
      { name: "B.Tech Mechanical", duration: "4 Years", seats: 300, fees: 350000, eligibility: "SRMJEEE" },
      { name: "M.Tech", duration: "2 Years", seats: 400, fees: 160000, eligibility: "SRMJEEE/GATE" },
    ],
    placements: {
      averagePackage: 600000,
      highestPackage: 4500000,
      medianPackage: 500000,
      placementRate: 80,
      topRecruiters: ["TCS", "Infosys", "Wipro", "Accenture", "Capgemini"],
    },
    ranking: { nirf: 36, india: 18 },
    accreditation: ["NAAC A++", "UGC"],
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Medical College", "Hospital"],
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&q=80",
    logo: "SRM",
    description: "SRM Institute offers a diverse range of programs with modern infrastructure. Known for its large campus and variety of specializations, it's a popular choice for students seeking private university education.",
    highlights: ["Huge Campus", "Medical Facilities", "International Collaborations", "Large Placement Drive"],
    cutoffs: [
      { exam: "SRMJEEE", year: 2024, category: "General", rank: 8000, branch: "Computer Science" },
    ],
    reviews: [
      {
        id: "r8",
        author: "Meena Sundar",
        avatar: "MS",
        rating: 4,
        date: "2024-03-22",
        title: "Good college for average budget",
        content: "SRM is a decent college with good infrastructure and placement support. The faculty quality varies but overall academic experience is satisfying. Good for those who want private college exposure.",
        pros: ["Good infrastructure", "Decent placements", "Variety of programs"],
        cons: ["Very large student population", "Inconsistent faculty quality"],
        batch: "2023",
        course: "B.Tech CSE",
        helpful: 76,
      },
    ],
    tags: ["Deemed", "Private", "Engineering", "Large Campus", "Tamil Nadu"],
    approved: true,
  },
  {
    id: "iit-madras",
    name: "Indian Institute of Technology Madras",
    shortName: "IIT Madras",
    location: { city: "Chennai", state: "Tamil Nadu" },
    type: "Government",
    established: 1959,
    rating: 4.8,
    reviewCount: 1100,
    fees: { btech: 218000, mtech: 20000 },
    courses: [
      { name: "B.Tech Computer Science", duration: "4 Years", seats: 110, fees: 218000, eligibility: "JEE Advanced" },
      { name: "B.Tech Aerospace Engineering", duration: "4 Years", seats: 50, fees: 218000, eligibility: "JEE Advanced" },
      { name: "B.Tech Ocean Engineering", duration: "4 Years", seats: 40, fees: 218000, eligibility: "JEE Advanced" },
      { name: "M.Tech", duration: "2 Years", seats: 220, fees: 20000, eligibility: "GATE" },
    ],
    placements: {
      averagePackage: 2000000,
      highestPackage: 24000000,
      medianPackage: 1750000,
      placementRate: 97,
      topRecruiters: ["Google", "Microsoft", "Intel", "NVIDIA", "Qualcomm"],
    },
    ranking: { nirf: 1, qs: 227, india: 1 },
    accreditation: ["NAAC A++", "NBA", "UGC"],
    facilities: ["Library", "Hostel", "Sports Complex", "Research Park", "Deer Park"],
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80",
    logo: "IIT-M",
    description: "IIT Madras holds the coveted #1 rank in NIRF for multiple consecutive years. Set in a lush forest campus in Chennai, it is India's top institute for engineering and technology research.",
    highlights: ["NIRF #1 Rank", "Research Park", "Forest Campus", "₹24 LPA Highest Package"],
    cutoffs: [
      { exam: "JEE Advanced", year: 2024, category: "General", rank: 75, branch: "Computer Science" },
      { exam: "JEE Advanced", year: 2024, category: "General", rank: 350, branch: "Aerospace" },
      { exam: "JEE Advanced", year: 2024, category: "OBC", rank: 52, branch: "Computer Science" },
    ],
    reviews: [
      {
        id: "r9",
        author: "Arun Krishnan",
        avatar: "AK",
        rating: 5,
        date: "2024-04-10",
        title: "India's crown jewel of engineering",
        content: "The forest campus, world-class research facilities, and absolutely brilliant professors make IIT Madras a transformative experience. NIRF #1 is well deserved.",
        pros: ["Beautiful campus", "Top research", "Excellent placements", "Great faculty"],
        cons: ["Very remote from city center", "Highly competitive environment"],
        batch: "2024",
        course: "B.Tech CSE",
        helpful: 287,
      },
    ],
    tags: ["IIT", "NIRF #1", "Government", "Research", "Top Ranked"],
    approved: true,
  },
];

export const STATES = [...new Set(colleges.map(c => c.location.state))].sort();
export const TYPES = [...new Set(colleges.map(c => c.type))];
export const EXAMS = ["JEE Advanced", "JEE Main", "BITSAT", "VITEEE", "CAT", "GATE", "SRMJEEE"];
export const COURSES_LIST = ["B.Tech", "M.Tech", "MBA", "B.E.", "PhD"];
